import type { NextPage } from 'next'
import Head from 'next/head'
import Comments from '../src/components/Comments/Comments'
import MainContent from '../src/components/MainContent'


const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>
      </header>
      <main>
        <MainContent></MainContent>
        <Comments></Comments>
      </main>
    </div>
  )
}

export default Home
