import { VStack, Text, Heading } from "@chakra-ui/react";
import type { NextPage } from "next";
import Head from "next/head";
import Link from "next/link";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header></header>
      <main>
        <VStack>
          <Heading>Jono's Markdown Blog</Heading>
          <Text>
            This blog is built using Next.js and ChakraUI. It is a prototype for
            a website that will contain useful Mathematics Resources and blog
            posts about how to best used them in tuition sessions. This blogs
            current features include: - Account creation and login implemented
            with Json Web Tokens - Page creation using a simple markdown file
            added to the /pages folder
          </Text>
          <Link href="/blog-00">blog 0</Link>
          <Link href="/blog-01">blog 1</Link>
        </VStack>
      </main>
    </div>
  );
};

export default Home;
